### ISSUE TITLE
 txCdsPredict: Permission denied / No such file or directory: 'tmp.cds'

### ISSUE THREAD

**Issue by lucianofrancoo** [LeiCao97/PreLnc#1]
Hello, im using ubuntu 20.10 (groovy). Im running PreLnc in a python2.7 environment and i get this error:
[PreLnc]start to extract features
sh: 1: txCdsPredict: Permission denied
Traceback (most recent call last):
  File "prelnc.py", line 412, in <module>
    main()
  File "prelnc.py", line 391, in main
    get_feature(inputfile,hexamer_dat,outputfile)
  File "prelnc.py", line 254, in get_feature
    temp=open("tmp.cds")
IOError: [Errno 2] No such file or directory: 'tmp.cds'
The command line i use is: python prelnc.py -i try.fa -m ../models/human_model.pkl -r ../models/human_hexamer.tsv -o example.txt
Any help on this error is welcome :(

**Comment by LeiCao97** [comment]
Thank you for your attention. I noticed the error "sh: 1: txCdsPredict: Permission denied". So guess if you have txCdsPredict configured. You need to configure txCdsPredict paths by modifying ~/.bashrc. Add the txCdsPredict path at the end of the ~/.bashrc file : for example, if PreLnc is in your directory '/home/lucianofrancoo/PreLnc', then run the commands:
(1) open the ~/.bashrc file:     vi ~/.bashrc
(2) write the path :      export PATH=$PATH:/home/lucianofrancoo/Prelnc/bin/
(3) save the ~/.bashrc file and compile it:    source ~/.bashrc

Hope this can help you. If you have any questions, please don't hesitate to contact me.

**Comment by lucianofrancoo** [comment]
I get the same error, the only difference is that I use nano instead of vi to edit ~/.bashrc, but i dont think this is a problem.
Any other idea what the problem is? :(
![Screenshot from 2021-03-12 12-29-15](https://user-images.githubusercontent.com/80530322/110962109-58b6ab00-832f-11eb-9dd0-07126fdae321.png)
![Screenshot from 2021-03-12 12-34-39](https://user-images.githubusercontent.com/80530322/110962112-59e7d800-832f-11eb-8029-ac499bc6fd5a.png)

**Comment by LeiCao97** [comment]
Is the path being written wrong？ I noticed the path: /home/luciano/Prelnc/bin 
Is the word capitalization:
"Prelnc" to "PreLnc" ？

**Comment by LeiCao97** [comment]
Is the path being written wrong？ I noticed the path: /home/luciano/Prelnc/bin&nbsp;&nbsp;
Is the word capitalization wrong？
"Prelnc" to "PreLnc" ？&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 12, 2021 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LeiCao97/PreLnc]  txCdsPredict: Permission denied / No such file or directory: 'tmp.cds' (#1)




 
I get the same error, the only difference is that I use nano instead of vi to edit ~/.bashrc, but i dont think this is a problem.
 Any other idea what the problem is? :(

**Comment by lucianofrancoo** [comment]
I corrected the path and it keeps throwing the same error. I also try with its built-in example and it follows with error. It will no be and error with the file "temp.cds" that appears at the end?
![Screenshot from 2021-03-12 13-52-15](https://user-images.githubusercontent.com/80530322/110972144-6faeca80-833a-11eb-8387-89705c32b258.png)
![Screenshot from 2021-03-12 13-52-19](https://user-images.githubusercontent.com/80530322/110972148-70476100-833a-11eb-8602-99469ef11899.png)

**Comment by LeiCao97** [comment]
The file "temp.cds"&nbsp; is created by txCdsPredict. If txCdsPredict didn't run successfully, the file&nbsp; temp.cds will not be created.&nbsp;
You can run txCdsPredict individually to verify that it works on your system.&nbsp;
Go to the PreLnc/bin directary, and run the command:
&nbsp; txCdsPredict


If it shows txCdsPredict usage, you can run txCdsPredict indivdually and then run python commands. Otherwise, it may be that some software permissions or environment configuration issues prevented txCdsPredict&nbsp; from running.





---Original---
From: ***@***.***&gt;
Date: Sat, Mar 13, 2021 00:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LeiCao97/PreLnc]  txCdsPredict: Permission denied / No such file or directory: 'tmp.cds' (#1)




 
I corrected the path and it keeps throwing the same error. I also try with its built-in example and it follows with error. It will no be and error with the file "temp.cds" that appears at the end?

**Comment by LeiCao97** [comment]
If txCdsPredict cannot run and still shows permission denied, you can give the permission to PreLnc and try again.
Go to your floder where PreLnc is. And run:
&nbsp; &nbsp;sudo chmod -R 777 PreLnc



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 13, 2021 00:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LeiCao97/PreLnc]  txCdsPredict: Permission denied / No such file or directory: 'tmp.cds' (#1)




 
I corrected the path and it keeps throwing the same error. I also try with its built-in example and it follows with error. It will no be and error with the file "temp.cds" that appears at the end?

**Comment by lucianofrancoo** [comment]
Woooo That fixed it!. With the command "sudo chmod -R 777 PreLnc" in the folder where PreLnc is. Thx have a nice day
